# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=50)),
                ('avg_rating', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
