# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 03:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=50)),
                ('avg_rating', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(default=b'', max_length=200)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
